# Generated by Django 4.2.11 on 2024-05-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_purchaseorder_issue_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Canceled", "Canceled"),
                    ("Completed", "Completed"),
                    ("Completed", "Pending"),
                ],
                max_length=50,
            ),
        ),
    ]
