# Generated by Django 4.2.11 on 2024-05-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_purchaseorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("", "---Select Staus---"),
                    ("Canceled", "Canceled"),
                    ("Completed", "Completed"),
                    ("Completed", "Pending"),
                ],
                max_length=50,
            ),
        ),
    ]
