# Generated by Django 4.2.11 on 2024-05-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_purchaseorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "---Select Staus---"),
                    ("Canceled", "Canceled"),
                    ("Completed", "Completed"),
                    ("Pending", "Pending"),
                ],
                max_length=50,
            ),
        ),
    ]
